
CREATE TABLE continent
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    code VARCHAR(255),
    CONSTRAINT pk_continent PRIMARY KEY (id)
);

ALTER TABLE resort
    ADD continent_id BIGINT;

ALTER TABLE resort
    ADD CONSTRAINT FK_RESORT_ON_CONTINENT FOREIGN KEY (continent_id) REFERENCES continent (id);

ALTER TABLE user_roles
    DROP CONSTRAINT pk_user_roles;