-- liquibase formatted sql

-- changeset ski-resort:1
CREATE TABLE event
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    date        date,
    image       VARCHAR(255),
    CONSTRAINT pk_event PRIMARY KEY (id)
);

-- changeset ski-resort:2
CREATE TABLE feedback
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    feedback_type VARCHAR(31),
    message       VARCHAR(255),
    rating        INTEGER,
    date_created  date,
    user_id       BIGINT                                  NOT NULL,
    event_id      BIGINT,
    resort_id     BIGINT,
    CONSTRAINT pk_feedback PRIMARY KEY (id)
);

-- changeset ski-resort:3
CREATE TABLE news
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    date        date,
    image       VARCHAR(255),
    CONSTRAINT pk_news PRIMARY KEY (id)
);

-- changeset ski-resort:4
CREATE TABLE resort
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    image       VARCHAR(255),
    CONSTRAINT pk_resort PRIMARY KEY (id)
);


-- changeset ski-resort:5
CREATE TABLE "user"
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username  VARCHAR(255)                            NOT NULL,
    password  VARCHAR(255),
    role      VARCHAR(255),
    firstname VARCHAR(255),
    lastname  VARCHAR(255),
    email     VARCHAR(255),
    image     VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

-- changeset ski-resort:6
ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

-- changeset ski-resort:7
ALTER TABLE feedback
    ADD CONSTRAINT FK_FEEDBACK_ON_EVENT FOREIGN KEY (event_id) REFERENCES event (id);

-- changeset ski-resort:8
ALTER TABLE feedback
    ADD CONSTRAINT FK_FEEDBACK_ON_RESORT FOREIGN KEY (resort_id) REFERENCES resort (id);

-- changeset ski-resort:9
ALTER TABLE feedback
    ADD CONSTRAINT FK_FEEDBACK_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (id);