

CREATE TABLE city
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    code VARCHAR(255),
    CONSTRAINT pk_city PRIMARY KEY (id)
);

CREATE TABLE country
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    code VARCHAR(255),
    CONSTRAINT pk_country PRIMARY KEY (id)
);

ALTER TABLE user_roles
    DROP CONSTRAINT user_roles_pkey;

ALTER TABLE continent
    DROP COLUMN city;

ALTER TABLE continent
    DROP COLUMN country;